name: Run E2E Tests

on: [pull_request, push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_DATABASE: findfriendapi
          POSTGRESQL_USERNAME: postgresql
          POSTGRESQL_PASSWORD: postgresql

      redis:
        image: bitnami/redis
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: redis

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e

        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://postgresql:postgresql@localhost:5432/findfriendapi?schema=public"
          REDIS_URL: "redis://:redis@localhost:6379/0"